#!/bin/python
import i3ipc
import subprocess
i3 = i3ipc.Connection()


def on_workspace_focus(i3, e):
    subprocess.run(['polybar-msg', 'hook', 'i3-mod', '1'])


subprocess.run(['polybar-msg', 'hook', 'i3-mod', '1'])
i3.on('workspace::focus', on_workspace_focus)
i3.on('workspace::init', on_workspace_focus)
i3.on('workspace::rename', on_workspace_focus)
i3.on('workspace::move', on_workspace_focus)
i3.on('workspace::empty', on_workspace_focus)
i3.main()
