#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail

function command_exists() {
  type "$1" &> /dev/null
}

DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
TOOL="i3_workspace_groups_tool.py"
command_exists "$TOOL" || TOOL="$DIR/../i3wsgroups/$TOOL"
if group="$(rofi -dmenu -p 'Enter workspace group name' -lines 0 -width 30)"; then
  [[ -n "$group" ]] || group=default
  "$TOOL" assign-workspace-to-group "$group"
else
  exit $?
fi
