#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
TOOL="$DIR/wrappers/i3_workspace_groups_tool.py"
if selected_group="$("$TOOL" list-groups | rofi -dmenu -p 'Switch to workspace group' -no-custom -lines 5 -width 30 )"; then
  "$TOOL" switch-active-group "$selected_group"
else
  exit $?
fi
